name: Deploy to Development

on:
  push:
    branches: [ dev ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Environment Variables
        run: echo "VITE_ENV=dev" > .env.development

      - name: Install Dependencies & Build Project
        run: |
          npm install
          rm -rf node_modules/.cache
          rm -rf dist
          npm run build

      - name: Deploy to S3
        run: |
          aws s3 sync ./dist s3://dev-sierra-frontend --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          S3_BUCKET: "dev-sierra-frontend"
          AWS_REGION: ${{ secrets.AWS_REGION }}